### ISSUE TITLE
Log messages like "node.send()  995898b3.0704c8,49600b6e.a8d844"

### ISSUE THREAD

**Issue by Caprico85** [Steve-Mcl/node-red-contrib-image-tools#11]
At first, let me say a big **THANK YOU** for this great node. But now to my issue:

jimp.js on lines 395, 409 and 424 contains
```console.log(`node.send()  ${node.id},${msg._msgid}`) ```

This produces quite a lot of unnecessary log messages. Can you please remove those lines or make them optional?

**Comment by Steve-Mcl** [comment]
Thanks for the kind words.  I will remove these in the next update soon.
