### ISSUE TITLE
Feature Request: Image Viewer Caption

### ISSUE THREAD

**Issue by rbflurry** [Steve-Mcl/node-red-contrib-image-tools#17]
I would like to be able to post a caption under the or above the image. I am currently doing this with a function node and the node.status 

![image](https://user-images.githubusercontent.com/22154114/84284582-632ae680-ab0a-11ea-857e-ad5eb50439f1.png)

``const map = msg.payload.body.predictions.map(prediction => {
      return `${prediction.label} (${(prediction.confidence * 100).toFixed(0)}%)`;
    })
    .join(", ");
    
    node.status({text:`${map}`});  
return msg;``

**Comment by Steve-Mcl** [comment]
Have you tried the "print" functions built in?

Look in the demos under node-red import -> examples -> node-red-contrib-image-tools for an example
