### ISSUE TITLE
Example for diff function

### ISSUE THREAD

**Issue by PauLL54** [Steve-Mcl/node-red-contrib-image-tools#21]
I cannot get the diff function to work. No output is generated. Probably I do something wrong.
Could you please provide an example with the diff function?

**Comment by Steve-Mcl** [comment]
> Could you please provide an example with the diff function?

See this closed issue - https://github.com/Steve-Mcl/node-red-contrib-image-tools/pull/12#issuecomment-612156429

**Comment by PauLL54** [comment]
Hi Steve,

Thank you for this example.
What I tried first was something like NotWorkingFlow.txt.
I was using file paths and was expecting that both j1 and j2 could be file paths.
This was fixed in file WorkingFlow.txt.

So now it is working fine!

Regards,
Paul Langemeijer



Van: Stephen McLaughlin <notifications@github.com>
Verzonden: Monday, December 28, 2020 2:25 PM
Aan: Steve-Mcl/node-red-contrib-image-tools <node-red-contrib-image-tools@noreply.github.com>
CC: PauLL54 <PaulLangemeijer@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Steve-Mcl/node-red-contrib-image-tools] Example for diff function (#21)


Could you please provide an example with the diff function?

See this closed issue - #12 (comment)<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSteve-Mcl%2Fnode-red-contrib-image-tools%2Fpull%2F12%23issuecomment-612156429&data=04%7C01%7C%7C35d9c33a13434e7533a008d8ab33fe46%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637447587080213217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hf6gcFsT7Z7Qvwl7N7fPaZdR7WmI00psW1ZF6UETuTA%3D&reserved=0>

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSteve-Mcl%2Fnode-red-contrib-image-tools%2Fissues%2F21%23issuecomment-751711467&data=04%7C01%7C%7C35d9c33a13434e7533a008d8ab33fe46%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637447587080213217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0tB1LzWwnt7%2B5B1C8SQIboEGHrBEJqM%2BG945RsUcIWE%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEEVG2VQ3T4SMZD5PA3DC5DSXCBLFANCNFSM4UCMELIA&data=04%7C01%7C%7C35d9c33a13434e7533a008d8ab33fe46%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637447587080223173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9a23pubh6PNRDwHo%2FRGEDTaNnlCF16pSYvNpe40YdEA%3D&reserved=0>.

[{"id":"2317a211.d8face","type":"jimp-image","z":"428cba09.3b8e94","name":"diff j1 / j2","data":"j1","dataType":"msg","ret":"img","parameter1":"j2","parameter1Type":"msg","parameter2":"","parameter2Type":"none","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","sendProperty":"payload","parameterCount":2,"jimpFunction":"diff","selectedJimpFunction":{"name":"diff","fn":"diff","description":"Using a mix of hamming distance and pixel diffing to compare images. Returns an image showing differences and msg.jobs[x].result will contain the proportion of different pixels (0-1), where 0 means the images are pixel identical","parameters":[{"name":"image2","type":"","required":true,"hint":"image to compare to"},{"name":"threshold","type":"num","required":false,"hint":"threshold ranges 0-1 (default: 0.1)"}]},"x":560,"y":920,"wires":[["51cfc368.35303c"]]},{"id":"51cfc368.35303c","type":"image viewer","z":"428cba09.3b8e94","name":"result","width":160,"data":"payload","dataType":"msg","x":730,"y":920,"wires":[["3922233f.8b79cc"]]},{"id":"2912865a.762bea","type":"comment","z":"428cba09.3b8e94","name":"↓diff result","info":"","x":739,"y":880,"wires":[]},{"id":"3922233f.8b79cc","type":"jimp-image","z":"428cba09.3b8e94","name":"","data":"payload","dataType":"msg","ret":"img","parameter1":"j2","parameter1Type":"msg","parameter2":"","parameter2Type":"none","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","parameterCount":0,"jimpFunction":"invert","selectedJimpFunction":{"name":"invert","fn":"invert","description":"invert the image colours","parameters":[]},"x":890,"y":920,"wires":[["c784948e.c499c8"]]},{"id":"c784948e.c499c8","type":"image viewer","z":"428cba09.3b8e94","name":"","width":160,"data":"payload","dataType":"msg","x":890,"y":960,"wires":[[]]},{"id":"a12f4db.f38dfb","type":"inject","z":"428cba09.3b8e94","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":190,"y":920,"wires":[["3600524f.2b6a8e"]]},{"id":"3600524f.2b6a8e","type":"function","z":"428cba09.3b8e94","name":"","func":"//msg.j1 = \"/home/pi/.node-red/lib/ui-media/lib/Camera/cam_79.jpg\"\n//msg.j2 = \"/home/pi/.node-red/lib/ui-media/lib/Camera/cam_80.jpg\"\n\n//msg.j1 = \"cam_79.jpg\"\n//msg.j2 = \"cam_80.jpg\"\n\nmsg.j1 = \"/home/pi/.node-red/public/cam_79.jpg\"\nmsg.j2 = \"/home/pi/.node-red/public/cam_80.jpg\"\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":350,"y":920,"wires":[["2317a211.d8face"]]}]

[{"id":"2317a211.d8face","type":"jimp-image","z":"428cba09.3b8e94","name":"diff j1 / j2","data":"j1","dataType":"msg","ret":"img","parameter1":"j2","parameter1Type":"msg","parameter2":"","parameter2Type":"none","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","sendProperty":"payload","parameterCount":2,"jimpFunction":"diff","selectedJimpFunction":{"name":"diff","fn":"diff","description":"Using a mix of hamming distance and pixel diffing to compare images. Returns an image showing differences and msg.jobs[x].result will contain the proportion of different pixels (0-1), where 0 means the images are pixel identical","parameters":[{"name":"image2","type":"","required":true,"hint":"image to compare to"},{"name":"threshold","type":"num","required":false,"hint":"threshold ranges 0-1 (default: 0.1)"}]},"x":800,"y":920,"wires":[["51cfc368.35303c"]]},{"id":"51cfc368.35303c","type":"image viewer","z":"428cba09.3b8e94","name":"result","width":160,"data":"payload","dataType":"msg","x":970,"y":920,"wires":[["3922233f.8b79cc"]]},{"id":"2912865a.762bea","type":"comment","z":"428cba09.3b8e94","name":"↓diff result","info":"","x":979,"y":880,"wires":[]},{"id":"ac244ec2.d4e0d","type":"jimp-image","z":"428cba09.3b8e94","name":"image1 base64-->jimp","data":"image1","dataType":"msg","ret":"img","parameter1":"image2","parameter1Type":"msg","parameter2":"","parameter2Type":"none","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","sendProperty":"payload","parameterCount":0,"jimpFunction":"none","selectedJimpFunction":{"name":"none","fn":"none","description":"Just loads the image.","parameters":[]},"x":240,"y":760,"wires":[["6b8da186.47cce"]]},{"id":"e2155333.084ed","type":"jimp-image","z":"428cba09.3b8e94","name":"image2 base64-->jimp","data":"image2","dataType":"msg","ret":"img","parameter1":"image2","parameter1Type":"msg","parameter2":"","parameter2Type":"none","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","sendProperty":"payload","parameterCount":0,"jimpFunction":"none","selectedJimpFunction":{"name":"none","fn":"none","description":"Just loads the image.","parameters":[]},"x":240,"y":820,"wires":[["b36e0aa.1c559f8"]]},{"id":"6b8da186.47cce","type":"change","z":"428cba09.3b8e94","name":"Set j1","rules":[{"t":"set","p":"j1","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"j1._name","pt":"msg","to":"j1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":410,"y":760,"wires":[["e2155333.084ed"]]},{"id":"b36e0aa.1c559f8","type":"change","z":"428cba09.3b8e94","name":"Set j2","rules":[{"t":"set","p":"j2","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"j2._name","pt":"msg","to":"j2","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":410,"y":820,"wires":[["2317a211.d8face","3b698ca1.c87b84"]]},{"id":"3922233f.8b79cc","type":"jimp-image","z":"428cba09.3b8e94","name":"","data":"payload","dataType":"msg","ret":"img","parameter1":"j2","parameter1Type":"msg","parameter2":"","parameter2Type":"none","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","parameterCount":0,"jimpFunction":"invert","selectedJimpFunction":{"name":"invert","fn":"invert","description":"invert the image colours","parameters":[]},"x":1130,"y":920,"wires":[["c784948e.c499c8"]]},{"id":"c784948e.c499c8","type":"image viewer","z":"428cba09.3b8e94","name":"","width":160,"data":"payload","dataType":"msg","x":1130,"y":960,"wires":[[]]},{"id":"a12f4db.f38dfb","type":"inject","z":"428cba09.3b8e94","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":190,"y":920,"wires":[["3600524f.2b6a8e"]]},{"id":"3600524f.2b6a8e","type":"function","z":"428cba09.3b8e94","name":"","func":"msg.image1 = \"/home/pi/.node-red/public/cam_79.jpg\"\nmsg.image2 = \"/home/pi/.node-red/public/cam_80.jpg\"\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":350,"y":920,"wires":[["ac244ec2.d4e0d"]]},{"id":"3b698ca1.c87b84","type":"debug","z":"428cba09.3b8e94","name":"test","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":680,"y":840,"wires":[]}]
