### ISSUE TITLE
Raspberry Node-red setup not working

### ISSUE THREAD

**Issue by alexliit** [Steve-Mcl/node-red-contrib-image-tools#22]
Hello

I'm trying to rotate webcvam images with a node-red flow with node-red-contrib-image-tools, but does not seem to work at all in my environment:
_RaspBerry PI 3   4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
Node.js v10.19.0
npm: '5.8.0'_

With a simple test node getting an image file I get 
"Error: property 'image' is not valid" in debug panel
"image cannot be empty" on the flow under the image node.

This is the test flow
`[{"id":"a45eca71.5e9ba8","type":"debug","z":"2ca01db9.9a6302","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":430,"y":940,"wires":[]},{"id":"ab23d54a.f85e68","type":"jimp-image","z":"2ca01db9.9a6302","name":"","data":"/tmp/camcancello1.jpg","dataType":"str","ret":"buf","parameter1":"90","parameter1Type":"num","parameter2":"false","parameter2Type":"bool","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","sendProperty":"payload","sendPropertyType":"msg","parameterCount":2,"jimpFunction":"rotate","selectedJimpFunction":{"name":"rotate","fn":"rotate","description":"rotate the image clockwise by a number of degrees. Optionally, a resize mode can be passed. If `false` is passed as the second parameter, the image width and height will not be resized.","parameters":[{"name":"deg","type":"num","required":true,"hint":"the number of degrees to rotate the image by"},{"name":"mode","type":"resizeMode|bool","required":false,"hint":"resize mode or a boolean, if false then the width and height of the image will not be changed"}]},"x":230,"y":660,"wires":[["a45eca71.5e9ba8"]]},{"id":"31541c9b.10c494","type":"inject","z":"2ca01db9.9a6302","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":80,"y":660,"wires":[["ab23d54a.f85e68"]]}]`

Even the user interface is not working properly: when doble-clicked the node on the flow, does no appear the node properties panel on the righ: if I click image node and another node, afteter closing the properties of the second node, the image node propierties panel appears, but very narrowed and I have to enlarge it to see the parameters.

Seems very odd for a very popular and used node !

Thanks for any suggestion!

Alex

**Comment by Steve-Mcl** [comment]
I dont have node v10 installed but I am certain at the time of development, I did. I dont quite understand what your issues are.  

> Even the user interface is not working properly: when doble-clicked the node on the flow, does no appear the node properties panel on the righ: if I click image node and another node, afteter closing the properties of the second node, the image node propierties panel appears, but very narrowed and I have to enlarge it to see the parameters. 

Could you paste some screen shots into a reply?

Also, could you try this demo flow...


![image](https://user-images.githubusercontent.com/44235289/103217033-833bbf00-490f-11eb-8ad5-5539d2d5a01e.png)

```
[{"id":"ab23d54a.f85e68","type":"jimp-image","z":"f77cda4d.5d7628","name":"","data":"payload","dataType":"msg","ret":"buf","parameter1":"90","parameter1Type":"num","parameter2":"false","parameter2Type":"bool","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","sendProperty":"payload","sendPropertyType":"msg","parameterCount":2,"jimpFunction":"rotate","selectedJimpFunction":{"name":"rotate","fn":"rotate","description":"rotate the image clockwise by a number of degrees. Optionally, a resize mode can be passed. If `false` is passed as the second parameter, the image width and height will not be resized.","parameters":[{"name":"deg","type":"num","required":true,"hint":"the number of degrees to rotate the image by"},{"name":"mode","type":"resizeMode|bool","required":false,"hint":"resize mode or a boolean, if false then the width and height of the image will not be changed"}]},"x":190,"y":260,"wires":[["76dc3020.7a995"]]},{"id":"31541c9b.10c494","type":"inject","z":"f77cda4d.5d7628","name":"","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":200,"y":200,"wires":[["541d025c.4cdd3c"]]},{"id":"541d025c.4cdd3c","type":"http request","z":"f77cda4d.5d7628","name":"","method":"GET","ret":"bin","paytoqs":"ignore","url":"https://picsum.photos/200/300","tls":"","persist":false,"proxy":"","authType":"","x":370,"y":200,"wires":[["b2d98251.3f9b"]]},{"id":"b2d98251.3f9b","type":"image viewer","z":"f77cda4d.5d7628","name":"","width":160,"data":"payload","dataType":"msg","x":530,"y":200,"wires":[["ab23d54a.f85e68"]]},{"id":"76dc3020.7a995","type":"image viewer","z":"f77cda4d.5d7628","name":"","width":160,"data":"payload","dataType":"msg","x":330,"y":260,"wires":[[]]}]
```

**Comment by alexliit** [comment]
Hello Steve!
Thanks for your reply!

It fails with "dataInput is empty (Image parameter)" error on the debug panel and "Error: image is null" in the flow panel.

Here an animated gif with your demo flow where I try to open the properties of the "rotate" node, but it oly open after I click on "timestamp" node and then close it's properties.

May be something is very wrong on my setup, but please note that it is not the only flow I have in my setup :-) 

Thanks!

Alex
![demo](https://user-images.githubusercontent.com/13914470/103224946-1503f600-4929-11eb-9ff8-c5621a8f5419.gif)

**Comment by Steve-Mcl** [comment]
Hi.

Could you open Dev tools (F12) and see if there are any errors?

Also, can you list what other nodes you are using?

Lastly, can you confirm the version of node-red and image tools please?

**Comment by alexliit** [comment]
Hello Steve.

This is the error I see when clicking on "rotate" node:
```
Uncaught TypeError: RED.tray.resize is not a function
    at HTMLSelectElement.eval (eval at <anonymous> (vendor.js:1), <anonymous>:710:26)
    at HTMLSelectElement.dispatch (vendor.js:4)
    at HTMLSelectElement.r.handle (vendor.js:4)
    at Object.trigger (vendor.js:4)
    at HTMLSelectElement.<anonymous> (vendor.js:4)
    at Function.each (vendor.js:2)
    at m.fn.init.each (vendor.js:2)
    at m.fn.init.trigger (vendor.js:4)
    at d (red.min.js:16)
    at b (red.min.js:16)
```
I use nodes like node-red-contrib-ftp-sftp, node-red-contrib-http-request, node-red-contrib-telegrambot, node-red-node-email,
among the "standard" ones (function, switch etc. etc.).

NodeRed release is 0.18.7
Node.js v10.19.0
npm: 5.8.0

Thanks!

**Comment by Steve-Mcl** [comment]
> NodeRed release is 0.18.7

This is your issue.  That is VERY OLD version of node-red.

current version of node-red is 1.2.6 

Is there anything stopping you from upgrading node-red?

**Comment by Steve-Mcl** [comment]
To follow up on the previous comment. 

As you are on a raspberry pi, if you are not using DOCKER and you are on Raspbian (or a Debian variant)  you can very easily upgrade to latest node-red using the install script [installing-and-upgrading-node-red](https://nodered.org/docs/getting-started/raspberrypi#installing-and-upgrading-node-red)

**Comment by alexliit** [comment]
Ok perfect.

I updated all the R-PI stack and did some tweak on the system in order to succeed in the nodered upgrade.
As you imagine is not always a risk-free activity.

But now I can tell it works!
thank you all for the support!

Alex
