### ISSUE TITLE
Preview of image cropping and an interactive way for choosing width and height

### ISSUE THREAD

**Issue by LimCC1234** [Steve-Mcl/node-red-contrib-image-tools#23]
Good day, sir. I am currently exploring this node for some image processing to pass through the tesseract node. For the cropping function, is there a way for us to preview the image being cropped without having to deploy the flow maybe? And also is there a easier way in node red that we can know how to choose the width and height? (I am currently using paint to determine all the xy coordinate, width and height).

**Comment by Steve-Mcl** [comment]
Hi @LimCC1234  

> For the cropping function, is there a way for us to preview the image being cropped without having to deploy the flow maybe? 

No, that is beyond the scope of its functionality. The design time part of a node-red node (where you design your flows / setup parameters etc) is "client side" whereas the nodes main functionality is "server side" (after you deploy).  

However, there is no reason you couldn't make a dashboard page that does this.  e.g...
* permit user to upload image (search the node-red flows pages for examples) - store the image in context and display on the page
* add a ui-form with necessary crop parameters (width / height etc)
* feed the form values to an image tools node to perform the crop.
* display the output on the dashboard.

This will permit you to apply as many crops as required.

> And also is there a easier way in node red that we can know how to choose the width and height? (I am currently using paint to determine all the xy coordinate, width and height). 

Again, same issue as above.  Also, as the image could literally come from anywhere (payload / file / internet) it really isnt feasible.  BUT, there is no reason why you couldnt create a dashboard page that utilises something like [this](https://stackoverflow.com/questions/32360656/get-coordinates-of-clicked-on-image-with-jquery)
 
![jxkZpm9iwA](https://user-images.githubusercontent.com/44235289/104844229-ee513380-58c6-11eb-800e-c808ed194937.gif)

**Comment by Steve-Mcl** [comment]
closing this issue for now.
