### ISSUE TITLE
The qrcode reading do not working with node-red-node-ui-webcam

### ISSUE THREAD

**Issue by jacobsiu** [Steve-Mcl/node-red-contrib-image-tools#25]
I try to feed image from camera ... it work if I use the camera input from node-red-contrib-browser-utils. However, it is not working with node-red-node-ui-webcam. In viewer node I can see the incoming image .. barcode reader just do not found the barcode  ( qrcode )

**Comment by Steve-Mcl** [comment]
Hi. 


Can you capture an image to file and share the the file? 

Use the file node to write your camera image to a file. 

Also, can you share your flow?

**Comment by Steve-Mcl** [comment]
No feedback - closing for now
