### ISSUE TITLE
SyntaxError: Unexpected token p in JSON at position 0

### ISSUE THREAD

**Issue by juggledad** [Steve-Mcl/node-red-contrib-image-tools#26]
Node-red: V1.3.5
image-tools: v1.4.0

This error pops up if you try to write an image but have set the "image" option to a 'buffer payload'. The example flow below is hacked out of one of the example flows provided with the node. Setting the "image' option to 'msg.payload' prevents the issue.

`[{"id":"788a48db.a25f48","type":"inject","z":"85ba953b.91f8e8","name":"flow.image","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"image","payloadType":"flow","x":320,"y":380,"wires":[["f3eae229.56d45","d3709ad5.2db4d","fb754df.bf4d4b"]]},{"id":"d3709ad5.2db4d","type":"jimp-image","z":"85ba953b.91f8e8","name":"written.jpg","data":"payload","dataType":"bin","ret":"img","parameter1":"written.jpg","parameter1Type":"str","parameter2":"true","parameter2Type":"bool","parameter3":"0","parameter3Type":"str","parameter4":"RESIZE_NEAREST_NEIGHBOR","parameter4Type":"Jimp","parameter5":"","parameter5Type":"","parameter6":"","parameter6Type":"","parameter7":"","parameter7Type":"","parameter8":"","parameter8Type":"","sendProperty":"payload","parameterCount":1,"jimpFunction":"write","selectedJimpFunction":{"name":"write","fn":"write","description":"Write to file. NOTE: You can specify an alternative file extension type to change the type. Currently support types are jpg, png, bmp.","parameters":[{"name":"filename","type":"str","required":true,"hint":"Name of the file","defaultType":"str"}]},"x":550,"y":380,"wires":[["376f8fc6.9f2678"]],"icon":"font-awesome/fa-image"},{"id":"fb754df.bf4d4b","type":"debug","z":"85ba953b.91f8e8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":310,"y":320,"wires":[]},{"id":"376f8fc6.9f2678","type":"debug","z":"85ba953b.91f8e8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":790,"y":380,"wires":[]}]`

**Comment by Steve-Mcl** [comment]
Hi Paul, I could probably handle better this but TBH it is a user error .  A buffer should be an array of numbers not a string.

Similar to entering the string "payload" for "buffer" on a change node (you get `Invalid 'to' JSON property`) 

I'll keep it in mind.

**Comment by juggledad** [comment]
True it is a user error, but the message gives you no hint as to what the problem is. I thought I'd create the issue incase someone else hits it so thy have a chance of figuring out what the cause and solution are.
