### ISSUE TITLE
How to save the image to a file

### ISSUE THREAD

**Issue by fallenruby** [Steve-Mcl/node-red-contrib-image-tools#29]
Hi, I've tried to use the file node to save the output as a JPG image, but with no luck. How can I do it? Thanks.

**Comment by Steve-Mcl** [comment]
Have you tried the built in examples? There is an example of that in one of the demos. 

CTRL+I -> examples -> node-red-contrib-image-tools

**Comment by fallenruby** [comment]
Hi, thank you. Yes, I've tried the examples but I can't see where the file is saved:

![image](https://user-images.githubusercontent.com/9852958/124197812-a2d6be80-dacf-11eb-9db4-26a05b3ea74c.png)

I can see the output in the viewer node, but where the file is stored?

**Comment by Steve-Mcl** [comment]
Load the demo called image manipulation. Run the example. A file called written.png will be created. As there is no file path specified it will be saved to the current working directory which is probably the `.node-red` folder. 

Just use a full file path if you want to save the file to a known location.

**Comment by fallenruby** [comment]
Oh yes sorry. Was really right there.

I'm sending photos through Telegram and printing them via a thermal printer:

![image](https://user-images.githubusercontent.com/9852958/124200283-3a8adb80-dad5-11eb-8a53-0a6aa9a8338e.png)

And it works quite well!!! =)

**Comment by Steve-Mcl** [comment]
Very nice. 

Glad your sorted.
