### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: srcx, srcy, srcw, srch must be numbers - shows in log

### ISSUE THREAD

**Issue by juggledad** [Steve-Mcl/node-red-contrib-image-tools#30]
macOS v11.6
Node-RED version: v2.0.5
Node.js  version: v14.16.0

While playing, I remove the function node and put in a change node and just set msg.qrx and msg.qry and leave out msg.qrh and msg.qrw. No error shows in the editor, but the flow stops. In the log I see this:

```
23 Sep 05:26:40 - [info] Started modified flows
(node:55294) UnhandledPromiseRejectionWarning: Error: srcx, srcy, srcw, srch must be numbers
    at Jimp.throwError (/Users/Paul/.node-red/node_modules/@jimp/utils/dist/index.js:33:13)
    at Jimp.blit (/Users/Paul/.node-red/node_modules/@jimp/plugin-blit/dist/index.js:49:34)
    at doProcess (/Users/Paul/.node-red/node_modules/node-red-contrib-image-tools/jimp.js:333:50)
    at imageProcessor (/Users/Paul/.node-red/node_modules/node-red-contrib-image-tools/jimp.js:442:49)
    at jimpNode._inputCallback (/Users/Paul/.node-red/node_modules/node-red-contrib-image-tools/jimp.js:543:25)
    at /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26
    at Object.trigger (/usr/local/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:149:13)
    at jimpNode.Node._emitInput (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)
    at jimpNode.Node.emit (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)
    at jimpNode.Node.receive (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:478:10)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:679:52)
    at processImmediate (internal/timers.js:461:21)
(node:55294) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**NOTE: if you set msg.qrh and msg.qrw to values, the issue goes away.**

flow causing the issue:
`[{"id":"ccfef74b6ecb45d5","type":"change","z":"613d89f61122f130","name":"","rules":[{"t":"set","p":"qrx","pt":"msg","to":"0","tot":"num"},{"t":"set","p":"qry","pt":"msg","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":480,"y":940,"wires":[["c68d34ff773e68b3","cb81305d3df506b1"]]},{"id":"8b43e788863473b7","type":"image viewer","z":"613d89f61122f130","name":"","width":160,"data":"merged","dataType":"msg","active":true,"x":970,"y":940,"wires":[[]]},{"id":"e9d6e4aa3d5ef412","type":"Barcode Generator","z":"613d89f61122f130","name":"QR Code","data":"serial","dataType":"msg","barcode":"qrcode","barcodeType":"barcode","options":"","optionsType":"ui","sendProperty":"qrBuffer","props":[],"x":280,"y":860,"wires":[["805a51f92ecfb136"]]},{"id":"e078a27cfe6e5cb4","type":"inject","z":"613d89f61122f130","name":"Serial","props":[{"p":"serial","v":"00001066","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":110,"y":860,"wires":[["e9d6e4aa3d5ef412"]]},{"id":"8469d6b7134ec10e","type":"jimp-image","z":"613d89f61122f130","name":"QR Merge","data":"template","dataType":"msg","ret":"img","parameter1":"qr","parameter1Type":"msg","parameter2":"qrx","parameter2Type":"msg","parameter3":"qry","parameter3Type":"msg","parameter4":"0","parameter4Type":"num","parameter5":"0","parameter5Type":"num","parameter6":"qrw","parameter6Type":"msg","parameter7":"qrh","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","sendProperty":"merged","sendPropertyType":"msg","parameterCount":7,"jimpFunction":"blit","selectedJimpFunction":{"name":"blit","fn":"blit","description":"blit the image with another Jimp image at x, y, optionally cropped","parameters":[{"name":"src","type":"","required":true,"hint":"the source image (a Jimp instance)","defaultType":"msg","defaultValue":"payload"},{"name":"x","type":"num","required":true,"hint":"the x position to blit the image"},{"name":"y","type":"num","required":true,"hint":"the y position to blit the image"},{"name":"srcx","type":"num","required":false,"hint":"the x position from which to crop the source image"},{"name":"srcy","type":"num","required":false,"hint":"the y position from which to crop the source image"},{"name":"srcw","type":"num","required":false,"hint":"the width to which to crop the source image"},{"name":"srch","type":"num","required":false,"hint":"the height to which to crop the source image"}]},"x":810,"y":940,"wires":[["8b43e788863473b7"]]},{"id":"f4c105aab5a31b18","type":"image viewer","z":"613d89f61122f130","name":"","width":160,"data":"qr","dataType":"msg","active":true,"x":110,"y":940,"wires":[["5442e3ac563082ba"]]},{"id":"c68d34ff773e68b3","type":"image viewer","z":"613d89f61122f130","name":"","width":160,"data":"template","dataType":"msg","active":true,"x":630,"y":940,"wires":[["8469d6b7134ec10e"]]},{"id":"5442e3ac563082ba","type":"jimp-image","z":"613d89f61122f130","name":"open template","data":"/Users/Paul/lily2.jpg","dataType":"str","ret":"img","parameter1":"","parameter1Type":"msg","parameter2":"","parameter2Type":"msg","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","sendProperty":"template","sendPropertyType":"msg","parameterCount":0,"jimpFunction":"none","selectedJimpFunction":{"name":"none","fn":"none","description":"Just loads the image.","parameters":[]},"x":300,"y":940,"wires":[["ccfef74b6ecb45d5"]]},{"id":"805a51f92ecfb136","type":"jimp-image","z":"613d89f61122f130","name":"","data":"qrBuffer","dataType":"msg","ret":"img","parameter1":"","parameter1Type":"msg","parameter2":"","parameter2Type":"msg","parameter3":"","parameter3Type":"msg","parameter4":"","parameter4Type":"msg","parameter5":"","parameter5Type":"msg","parameter6":"","parameter6Type":"msg","parameter7":"","parameter7Type":"msg","parameter8":"","parameter8Type":"msg","sendProperty":"qr","sendPropertyType":"msg","parameterCount":0,"jimpFunction":"none","selectedJimpFunction":{"name":"none","fn":"none","description":"Just loads the image.","parameters":[]},"x":450,"y":860,"wires":[["f4c105aab5a31b18"]]},{"id":"cb81305d3df506b1","type":"debug","z":"613d89f61122f130","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":730,"y":880,"wires":[]}]`

**Comment by Steve-Mcl** [comment]
Hi Paul, thanks for reporting this.

I had missed off an await on the Jimp call (so the error wasnt being caught by the `try...catch` handler).

This is what happens now after fixing that...

![image](https://user-images.githubusercontent.com/44235289/134773407-2125c93b-175d-4aec-ac89-4198b1c27b81.png)

I will publish an update in due course.

Cheers, Steve.

**Comment by Steve-Mcl** [comment]
PS, I had some unwated requires in the function node in that [original thread](https://discourse.nodered.org/t/node-red-contrib-image-tools-combining-images/50081/2?u=steve-mcl) - I have edited the post removed them and that example should now import and work :)
