### ISSUE TITLE
Wrong filename or url cause nodered to crash

### ISSUE THREAD

**Issue by ekremparlak** [Steve-Mcl/node-red-contrib-image-tools#33]
If i set payload to wrong local filename that dosent exist or wrong url nodered crashes.

Logs;
for dns: 
````
28 Jan 16:50:33 - [red] Uncaught Exception:
28 Jan 16:50:33 - [error] Error: getaddrinfo ENOTFOUND aaas.sad
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
````
for file;
````
28 Jan 16:39:00 - [red] Uncaught Exception:
28 Jan 16:39:00 - [error] Error: ENOENT: no such file or directory, open 'aaaaasd'
````

**Comment by Steve-Mcl** [comment]
Hi. Have you updated to latest version. There was an issue I found earlier today.

**Comment by ekremparlak** [comment]
Update fix the problem. 
I was installed this node yesterday and didn't think to look for updates :(

**Comment by Steve-Mcl** [comment]
@ekremparlak no worries. Thanks for taking the time to report it. 

Please close this issue if you are happy it's now working properly :)
