### ISSUE TITLE
[QUESTION] how to resolve Error: ENAMETOOLONG: name too long?

### ISSUE THREAD

**Issue by ani-rudh** [Steve-Mcl/node-red-contrib-image-tools#42]
Hi, I am trying to send png/jpeg images as mqtt payload from a service and view it on node-red using this tool. I get this error even after heavily compressing the image data. I am using opencv-python lib to encode the image as b64 string. 

Is there anything to pay attention to when compressing or what is actually this error with the "name"?

Any guidance/help in this matter would be great :)

I have verified the images on a b64 decoder tool and it seems to be fine.

Thanks!

**Comment by Steve-Mcl** [comment]
Sorry for the very late reply. 

If this is still an issue, please re-open this comment.
