### ISSUE TITLE
€ symbol in Font

### ISSUE THREAD

**Issue by gitmacer** [Steve-Mcl/node-red-contrib-image-tools#43]
I tried to print a € symbol with the print function but sadly it prints a ? or nothing.
I would highly apreciate if you could update the font to include the € symbol.
Also more font sizes would be good.

**Comment by Steve-Mcl** [comment]
Unfortunately, the fonts provided by Jimp are limited. You can however build your own fonts.

Here is a demo:

![image](https://github.com/Steve-Mcl/node-red-contrib-image-tools/assets/44235289/01ab5ff2-ec4e-4242-b3c0-c87ed0ee4c2a)


the instructions to build a font are here: https://github.com/jimp-dev/jimp/issues/419#issuecomment-1717950781

**Comment by gitmacer** [comment]
Thank you for replying. I actually already added € to the Fonts 8, 16, 32, 64, 128 white and black in the jimp release. But last time I tried the nodered package wasn't updated which these changes.

https://github.com/jimp-dev/jimp/pull/1249

**Comment by Steve-Mcl** [comment]
oh, excellent. 

As it happens, I have just updated this package which updates all dependencies - so hopefully this is a non issue now. 

V2.1.0 should appear in the node-red catalog with 30 mins (usually)
