### ISSUE TITLE
Incorrect dependency for bwip-js

### ISSUE THREAD

**Issue by sgruby** [Steve-Mcl/node-red-contrib-image-tools#45]
It appears that the updated dependency for bwip-js is listed as:

```
"bwip-js": "^4.20",
```

where the actual version should be 4.2.0 so the package won't install.

**Comment by Steve-Mcl** [comment]
node-red library updated to v2.1.1 - it can take up to 30 mins to populate the node-red catalog (use `npm install node-red-contrib-image-tools@latest` to get the update quicker)
