### ISSUE TITLE
trying to convolve one image with another

### ISSUE THREAD

**Issue by moryoav** [Steve-Mcl/node-red-contrib-image-tools#6]
I'm trying to find one small image ('B') inside another (larger) image ('A').
I tried convolving A.*B - I simply wrote in the convolution kernel, instead of an actual kernel, the variable containing the smaller image B. This does not work.
Is there a different approach to doing that?

**Comment by Steve-Mcl** [comment]
Hi, I'd like to understand your issue & resolve it.

could you please post a demo flow showing what you hoe to happen vs what actually happens?

something like below - that a user posted - that helped me greatly in resolving the issue

https://github.com/Steve-Mcl/node-red-contrib-image-tools/pull/12#issuecomment-611303107 


Cheers.


PS: I have just updated to V1.x & the issue may now be resolved?

**Comment by Steve-Mcl** [comment]
@moryoav I'm gonna close this for now as i cannot understand your requirement.

Please re-open if necessary & I will take a look if you can provide a demo flow.

thanks for the interest.
